# Generated by Django 5.0.3 on 2024-05-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nimi', models.TextField(default='', max_length=100)),
                ('hinta', models.FloatField(default=0, max_length=250)),
                ('kuvaus', models.TextField(default='', max_length=250)),
                ('tuotekuva', models.ImageField(default='', upload_to='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
