# Generated by Django 5.0.3 on 2024-05-30 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nimi', models.TextField(default='', max_length=100)),
                ('hinta', models.FloatField(default=0, max_length=250)),
                ('kuvaus', models.TextField(default='', max_length=250)),
                ('tuotekuva', models.ImageField(default='', upload_to='')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tuote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'default_permissions': 'view',
            },
        ),
    ]
