# Generated by Django 5.0.3 on 2024-05-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuote', '0002_alter_tuotemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuotemodel',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='tuotemodel',
            old_name='owner',
            new_name='luonut',
        ),
    ]
