# Generated by Django 5.0.3 on 2024-05-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuotemodel',
            options={'default_permissions': ['view'], 'ordering': ['created']},
        ),
    ]
