# Generated by Django 5.0.3 on 2024-05-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuote', '0003_alter_tuotemodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuotemodel',
            old_name='luonut',
            new_name='owner',
        ),
    ]
