# Generated by Django 5.0.3 on 2024-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_tuotekuva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nimi', models.TextField(default='')),
                ('hinta', models.FloatField(default=0)),
                ('kuvaus', models.TextField(default='')),
                ('tuotekuva', models.ImageField(default='', upload_to='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
